export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PRODUCTS_ROUTE = '/products'
export const EDITOR_ROUTE = '/products/editor'
export const PRODUCT_ROUTE = '/product'
export const MAIN_ROUTE = '/'
